stages:
  - deploy

image: docker:latest

variables:
  REGISTRY: ${CI_REGISTRY}/nnniruuu/crm-backend
  SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

deploy_dev:
  stage: deploy
  only:
    refs:
      - master
      - dev
  image: alpine
  before_script:
    - apk update
    - apk add openssh-client
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 600 id_rsa
  script:
    - ssh -o StrictHostKeyChecking=no -i id_rsa root@193.3.168.81 << 'EOF'
        cd /var/www/cfhelper.com/cloudflare &&
        echo "Current directory: $(pwd)" &&
        git reset --hard &&
        git checkout master &&
        git pull &&
        echo "Sourcing .bashrc..." &&
        source ~/.bashrc &&
        echo "Running npm install..." &&
        npm install &&
        echo "Running npm run build..." &&
        npm run build &&
        echo "Restarting PM2 process..." &&
        pm2 restart cloudflare
      EOF
